### PR TITLE
Fix suggestions cache miss handling for missing files

### LINKED ISSUE #876: [BUG] - Movie suggestions stuck on loading/ not displaying
### Description

Awesome app you have here!

Movie suggestions stuck on loading/ not displaying  after updating to 0.4.2

### Reproduction steps

_No response_

### App Version

0.4.2

### Server Version

10.11.6

### Device

_No response_

### Logs

```bash
Wholphin: Failed to fetch suggestions
Wholphin: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@88a2598


java.io.FileNotFoundException: /data/user/0/com.github.damontecres.wholphin/cache/suggestions/f0c73868f5a1416db050ef6e068677af_f137a2dd21bbc1b99aa5c0f6bf02a805_Movie.json: open failed: ENOENT (No such file or directory)
02-11 19:03:31.882  3762  1768 E Wholphin: 	at libcore.io.IoBridge.open(IoBridge.java:492)
02-11 19:03:31.882  3762  1768 E Wholphin: 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
02-11 19:03:31.882  3762  1768 E Wholphin: 	at com.github.damontecres.wholphin.services.SuggestionsCache$get$2.invokeSuspend(SuggestionsCache.kt:65)
02-11 19:03:31.882  3762  1768 E Wholphin: 	at com.github.damontecres.wholphin.services.SuggestionsCache$get$2.invoke(Unknown Source:8)
02-11 19:03:31.882  3762  1768 E Wholphin: 	at com.github.damontecres.wholphin.services.SuggestionsCache$get$2.invoke(Unknown Source:4)
02-11 19:03:31.882  3762  1768 E Wholphin: 	at com.mayakapps.kache.InMemoryKache$internalPutAsync$deferred$1.invokeSuspend(InMemoryKache.kt:190)
02-11 19:03:31.882  3762  1768 E Wholphin: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
02-11 19:03:31.882  3762  1768 E Wholphin: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
02-11 19:03:31.882  3762  1768 E Wholphin: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:124)
02-11 19:03:31.882  3762  1768 E Wholphin: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
```

### PR DESCRIPTION
**Pull request by zoro11031**
## Description
Fix a bug where movie suggestions would get stuck loading when the on-disk cache file doesn't exist.

### Related issues
Fixes #876

### Testing
Ran unit tests locally. 

## Screenshots
N/A

## AI or LLM usage
Used AI to add testing for this scenario to unit test

### CODE REVIEW

File: app/src/main/java/com/github/damontecres/wholphin/services/SuggestionsCache.kt [hunk 1]
```diff
@@ -59,16 +59,21 @@ class SuggestionsCache
...
             return memoryCache.getOrPut(key) {
-                try {
-                    mutex.withLock {
-                        File(cacheDir, "$key.json").inputStream().use {
+                mutex.withLock {
+                    val cacheFile = File(cacheDir, "$key.json")
+                    if (!cacheFile.exists()) {
+                        return@withLock null
+                    }
+                    try {
```
Comment (damontecres) [inline app/src/main/java/com/github/damontecres/wholphin/services/SuggestionsCache.kt]: Just to be extra safe:
```suggestion
                    try {
                        val cacheFile = File(cacheDir, "$key.json")
                        if (!cacheFile.exists()) {
                            return@withLock null
                        }

```

**Review by damontecres — COMMENTED** [review]
Two minor comments, otherwise LGTM!
